openapi: '3.0.0'
info:
  title: Authentication api
  description: An API for authentication
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0-oas3
servers:
  - url: https://localhost:8080/gestionCours
paths:
  /subjects:
    post:
      operationId: createSubject
      description: create a subject
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subject'
      responses:
        '201':
          description: created
        '401':
          description: unexpected error
        '403':
          description: forbidden
        '404':
          description: not found
    get:
      description: get the list of all subjects
      operationId: getSubjects
      parameters:
        - in: path
          name: allSujects
          required: true
          schema:
            type: array
            items:
              $ref: '#/components/schemas/SubjectList'
      responses:
        '200':
          description: success
        '401':
          description: unexpected error

  /enrollments:
    post:
      operationId: createEnrollment
      description: create an Enrollment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Enrollment'
      responses:
        '201':
          description: created
        '401':
          description: unexpected error
        '403':
          description: forbidden
        '404':
          description: not found
    get:
      description: get the list of all enrollments
      operationId: getEnrollments
      parameters:
        - in: path
          name: allEnrollemnts
          required: true
          schema:
            type: array
            items:
              $ref: '#/components/schemas/EnrollmentList'
      responses:
        '200':
          description: success
        '401':
          description: unexpected error

components:
  schemas:
    Subject:
      type: object
      required:
        - name
          - credits_etcs
      properties:
        name:
          type: string
        credits_etcs:
          type: integer
          format: int64

    SubjectList:
      allOf:
        - $ref: '#/components/schemas/Subject'
        - type: object
      properties:
        id:
          type : integer
          format: int64
    User:
      type: object
      required:
        - e_mail
        - first_name
        - last_name
        - password
        - user_role
      properties:
        e_mail:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        password:
          type: string
        user_role:
          type: string
    Enrollment:
      type: object
      required:
        - subject_id
        - e_mail
      properties:
        subject_id:
          type: integer
          format: int64
        e_mail:
          type: string
    EnrollmentList:
      allOf:
        - $ref: '#/components/schemas/Enrollment'
        - type: object
      properties:
        id:
          type: integer
          format: int64






