version: '2'

services:
    mysql:
        build: ../images/mysql
        environment:
         - MYSQL_DATABASE=gestioncours
         - MYSQL_USER=amtprojet2
         - MYSQL_PASSWORD=yourpass
         - MYSQL_ROOT_PASSWORD=root"
        ports:
         - "3306:3306"
       